<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Title>Gera.Chess.Standard</Title>
    <Description>Fork of Gera.Chess library adapted for .NET Standard 2.1. Supports SAN and FEN parsing, move validation, legal position generation, auto endgame detection (insufficient material, repetition, fifty-move rule), event handlers, and more!</Description>
    <Authors>Mohammad Diab</Authors>
    <PackageTags>chess;C#;SAN;FEN;.NET Standard;game logic</PackageTags>
    <RepositoryUrl>https://github.com/Mohammad-Diab/ChessLib</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
  </ItemGroup>

</Project>
